### ISSUE TITLE
How do I use it?

### ISSUE THREAD

**Issue by KGTasa** [B3n30/citra_system_archives#12]
I am a big noob. How do I use it? Do I download it? The most advanced thing I know is how to clone something from github using cmd, so you get the idea. Thanks

**Comment by B3n30** [comment]
this is a helper repo for github.com/citraemu/citra. For the usage look there

**Comment by KGTasa** [comment]
I meant how do I use this to get system files

**Comment by B3n30** [comment]
you don't get system files with this. This is to generate files that look similar to the 3DS system files, so that if games are played with Citra and the game needs system files it can use those replacements

**Comment by KGTasa** [comment]
yes, so how do I get this to generate system files? that was my question

**Comment by B3n30** [comment]
you need a linux system with the required stuff installed and then you just execute the run.sh

**Comment by KGTasa** [comment]
for linux i only have a raspberry pi, will that do?

**Comment by B3n30** [comment]
yes
